### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by fabaff** [s0md3v/Photon#98]
Hmm, PyPI tell me that the latest release is [1.1.9](https://pypi.org/project/photon/). The changelog says it's 1.1.4 (I assume that the changelog wasn't updated) and the latest release on GitHub is 1.1.5.

Also, it seems that the `setup.py` file is missing.

Usually, I don't care where the package source is coming  from (the Fedora Package guidelines don't make a statement about that) but I would be nice if it doesn't change too often.

**Comment by s0md3v** [comment]
Well, Photon is on `1.1.5` right now but the changelog wasn't updated after `1.1.4`.

When I uploaded Photon to PyPi, I was quite new to `PyPi` and I messed up. I deleted the build from there and tried to upload it again which ofc failed because PyPi doesn't allow you to upload the same version so I uploaded it again after fixing what I think was causing the trouble and it didn't work again so I uploaded it with +1 version number and......we are here, on `1.1.9`.

**Comment by fabaff** [comment]
I see. It would be nice if they are synced :wink: 

BTW, thanks for your quick response.

**Comment by fabaff** [comment]
This is not resolved.

**Comment by s0md3v** [comment]
There's only one way to resolve this.
PyPi release is at `1.1.9` while Github release is at `1.1.5`, so now when `1.1.6` comes out, we can name `PyPi` release `1.1.9.1` and we can keep doing this until we reach `1.1.10` where we can finally merge them.

Do you have a better idea?
